name: Build and Deploy Blazor App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: ~/.docker/buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      run: |
        docker build -f C:/Users/abbz2/source/repos/Automation/Automation/Dockerfile -t my-blazor-app .



    - name: Run tests (if applicable)
      run: |
        docker run --rm my-blazor-app dotnet test

    - name: Push Docker image to Docker Hub
      if: github.ref == 'refs/heads/master'
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag my-blazor-app yourusername/my-blazor-app:latest
        docker push yourusername/my-blazor-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to server (your server setup)
      run: |
        # Use SSH to deploy to your server or any cloud service
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} user@yourserver 'docker pull yourusername/my-blazor-app:latest && docker run -d -p 80:80 yourusername/my-blazor-app:latest'
